using System;
using System.Collections.Generic;
using JetBrains.Annotations;
using MessagePack;

namespace MarginTrading.AccountsManagement.Contracts.Events
{
    /// <summary>
    /// Event is generated by Trading Engine when accounts are blocked.
    /// </summary>
    [MessagePackObject]
    public class AccountsBlockedForDeletionEvent: BaseEvent
    {
        /// <summary>
        /// List of blocked account id's.
        /// </summary>
        [Key(2)]
        public List<string> BlockedAccountIds { get; }
        
        /// <summary>
        /// Dictionary of failed accounts with reason.
        /// </summary>
        [Key(3)]
        public Dictionary<string, string> FailedAccountIds { get; }
        
        public AccountsBlockedForDeletionEvent([NotNull] string operationId, DateTime eventTimestamp, 
            List<string> blockedAccountIds, Dictionary<string, string> failedAccountIds) 
            : base(operationId, eventTimestamp)
        {
            BlockedAccountIds = blockedAccountIds;
            FailedAccountIds = failedAccountIds;
        }
    }
}