// Copyright (c) 2019 Lykke Corp.

using System;
using System.Collections.Generic;
using JetBrains.Annotations;
using MessagePack;

namespace MarginTrading.AccountsManagement.Contracts.Events
{
    /// <summary>
    /// Event is generated by Trading Engine when accounts are blocked.
    /// </summary>
    [MessagePackObject]
    public class AccountsBlockedForDeletionEvent: BaseEvent
    {   
        /// <summary>
        /// Dictionary of failed accounts with reason.
        /// </summary>
        [Key(2)]
        public Dictionary<string, string> FailedAccountIds { get; }
        
        public AccountsBlockedForDeletionEvent([NotNull] string operationId, DateTime eventTimestamp, 
            Dictionary<string, string> failedAccountIds) 
            : base(operationId, eventTimestamp)
        {
            FailedAccountIds = failedAccountIds;
        }
    }
}