// Copyright (c) 2019 Lykke Corp.

using System;
using System.Collections.Generic;
using JetBrains.Annotations;
using MessagePack;

namespace MarginTrading.AccountsManagement.Contracts.Events
{
    /// <summary>
    /// Event is generated by AccountsManagement when accounts are marked as deleted.
    /// </summary>
    [MessagePackObject]
    public class AccountsMarkedAsDeletedEvent: BaseEvent
    {
        /// <summary>
        /// Dictionary of account id's that failed validation.
        /// </summary>
        [Key(2)]
        public Dictionary<string, string> ValidationFailedAccountIds { get; }

        public AccountsMarkedAsDeletedEvent([NotNull] string operationId, DateTime eventTimestamp,
            Dictionary<string, string> validationFailedAccountIds)
            : base(operationId, eventTimestamp)
        {
            ValidationFailedAccountIds = validationFailedAccountIds;
        }
    }
}