using System;

namespace MarginTrading.AccountsManagement.Contracts.Api
{
    public class AccountChargeManuallyRequest
    {
        /// <summary>
        /// The amount of money to add or deduct from the account's balance 
        /// </summary>
        public decimal AmountDelta { get; set; }
        
        /// <summary>
        /// Reason of modification
        /// </summary>
        public string Reason { get; set; }
        
        /// <summary>
        /// The unique id of operation.<br/>
        /// Two operations with equal type and id are considered one operation, all duplicates are skipped.<br/>
        /// It would be a nice idea to use a <see cref="Guid"/> here.<br/>
        /// </summary>
        /// <remarks>
        /// Not required. If not provided it is autogenerated.
        /// </remarks>
        public string OperationId { get; set; }
    }
}